fixed incorrect var name and bad error checks

diff --git a/wiretap b/wiretap
--- a/wiretap
+++ b/wiretap
@@ -9,11 +9,6 @@ usage() {
     exit 2
 }
 
-confirm_interface() {
-    local device="$1"
-    ip link show dev $device 2>&1
-}
-
 if ! command -v ip > /dev/null 2>&1
 then
     echo "Missing depandancy: ip"
@@ -41,51 +36,21 @@ case "$action" in
         ;;
 esac
 
-[[ confirm_interface "$interface" ]] || {
-    echo "Invalid interface: $interface" >&2
-    exit 2
-}
+if [[ -z "$interface" || -z "$span" ]]; then
+    usage
+fi
 
-[[ confirm_interface "$span" ]] || {
-    echo "Invalid interface: $span" >&2
-    exit 2
-}
+if ! ip link show dev "$interface" >/dev/null 2>&1; then
+    echo "Error: source interface '$interface' does not exist." >&2
+    exit 1
+fi
+
+if ! ip link show dev "$span" >/dev/null 2>&1; then
+    echo "Error: SPAN interface '$span' does not exist." >&2
+    exit 1
+fi
 
 add_tap() {
-    # rollback_tap() {
-    #     tc qdisc del $i ingress 2>/dev/null || true
-    #     tc qdisc del $i root 2>/dev/null || true
-    # }
-
-    # if ! tc qdisc add dev $i ingress; then
-    #     echo "Error: failed to add ingress qdisk to '$i'." >&2
-    #     return 1
-    # fi
-
-    # if ! tc filter add dev $i parent ffff: \ 
-    #     protocol all u32 match u8 0 0 \
-    #     action mirred egress mirror dev $SPAN_PORT
-    # then
-    #     echo "Error: failed to add ingress mirror filter." >&2
-    #     rollback_tap
-    #     return 1
-    # fi
-
-    # # Capture Egress Traffic (thx @nukingdragons)
-    # if ! tc qdisc add dev $i handle 1: root prio; then
-    #     echo "Error: failed to add root prio qdisc to '$i'." >&2
-    #     rollback_tap
-    #     return 1
-    # fi
-
-    # if ! tc filter add dev $i parent 1: \
-    #     protocol all u32 match u8 0 0 \
-    #     action mirred egress mirror dev $SPAN_PORT
-    # then
-    #     echo "Error: failer to add egress mirror filter." >&2
-    #     rollback_tap
-    #     return 1
-    # fi
 
     if ! tc qdisc add dev "$interface" clsact; then
          echo "Error: failed to add qdisk to '$interface'." >&2
@@ -95,7 +60,7 @@ add_tap() {
     if ! tc filter add dev "$interface" ingress \
         protocol all \
         u32 match u8 0 0 \
-        action mirred egress mirror dev "$SPAN_PORT"
+        action mirred egress mirror dev "$span"
     then
         echo "Error: failed to add ingress mirror filter." >&2
         remove_tap
@@ -116,8 +81,6 @@ add_tap() {
 }
 
 remove_tap() {
-    #tc qdisc del dev $interface ingress
-    #tc qdisc del dev $interface root
 
     tc qdisc del dev "$interface" clsact
 
@@ -127,12 +90,12 @@ remove_tap() {
 case "$action" in
     add)
         logger -t "$LOGGER_TAG" \
-            "Taping interface ($interfac) to span port ($span)"
+            "Taping interface ($interface) to span port ($span)"
         add_tap $interface $span
         ;;
     remove)
         logger -t "$LOGGER_TAG" \
-            "removing tap from interface ($interfac) connected to span port ($span)"
+            "removing tap from interface ($interface) connected to span port ($span)"
         remove_tap
         ;;
 esac
